schema_version = "1.0.0"

id = "generate_tree_plugin"
version = "1.1.2"
name = "Generate Tree Plugin"
tagline = "Procedurally generates low-poly trees"
maintainer = "Yuriy <yura.imco@gmail.com>"
type = "add-on"

website = "https://github.com/YGForge"

tags = ["Add Mesh", "Object"]

blender_version_min = "5.0.1"

license = [
  "SPDX:GPL-3.0-or-later",
]
